site:
  url: 'http://local.test/addon-taxonomy/demo/'

directories:
  web: ${directories.base}

theme:
  activate:
    - core/basic

addons:
  activate:
    - taxonomy
    - php-content

templates:
  site:
    name: Demo Leafcutter site

cache:
  driver: ephemeral
